using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class controller : MonoBehaviour
{
    Animator animator;

    void Awake()
    {
        TryGetComponent(out animator);
    }
    // Start is called before the first frame update

    // Update is called once per frame
    void Update()
    {
        //入力ベクトルの取得
        var horizontal = Input.GetAxis("Horizontal");
        var vertical = Input.GetAxis("Vertical");
        var velocity = new Vector3(horizontal, 0, vertical).normalized;
        var speed = Input.GetKey(KeyCode.LeftShift) ? 2: 1;

        //移動方向を向く
        if( velocity.magnitude > 0.5f)
        {
           transform.rotation = Quaternion.LookRotation(velocity, Vector3.up);
        }
     


        //移動速度をAnimatorに反映
        animator.Setfloat("Speed" , velocity.magnitude * speed , 0.1f , Time.deltaTime);

    }
}
